### ISSUE TITLE
Metadata version mismatch for module

### ISSUE THREAD

**Issue by juni381** [7leads/ngx-cookie-service#12]
hello , i am using CookieSevice , first i have installl them by 
npm install ngx-cookie --save then import it in Module
then i created cookie backend for fake token generating , now i am getting error below :--

Error: Metadata version mismatch for module F:/edcertsWallet/node_modules/ngx-cookie/index.d.ts, found version 4, expected 3, resolving symbol AppModule in F:/edcertsWallet/src/app/app.module.ts, resolving symbol AppModule in F:/edcertsWallet/src/app/app.module.ts, resolving symbol AppModule in F:/edcertsWallet/src/app/app.module.ts
    at syntaxError (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:25111:23)
    at StaticReflector.simplify (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:25123:13)
    at StaticReflector.annotations (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:24553:41)
    at _getNgModuleMetadata (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (F:\edcertsWallet\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (F:\edcertsWallet\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by CunningFatalist** [comment]
Hello,

I am afraid this question is best asked over at StackOverflow, as it seems to be an integration problem and not a problem with the cookie service itself - at least as far as I can tell. What you can and probably should try is to update your packages with npm/yarn. If that does not work, open a StackOverflow question, mention everything you tried to fix the problem and add your package.json contents (people will probably want to inspect them).

Cheers and good luck with your bug hunt

**Comment by juni381** [comment]
Thanks man.. for your advice it worked :)

**Comment by CunningFatalist** [comment]
Nice, you're welcome :smile:

**Comment by CunningFatalist** [comment]
Nice, you're welcome :smile:

**Comment by CunningFatalist** [comment]
Nice, you're welcome :smile:

**Comment by CunningFatalist** [comment]
Nice, you're welcome :smile:
