### ISSUE TITLE
NotYetImplemented in SSR

### ISSUE THREAD

**Issue by testica** [7leads/ngx-cookie-service#26]
## Actual Behavior
Doesn't work with SSR
Output:
```
Error: NotYetImplemented
    at Object.module.exports.exports.nyi (/var/task/dist/server.js:25776:9)
    at CookieService.module.exports.CookieService.check (/var/task/dist/server.js:178063:47)
    at CookieService.module.exports.CookieService.get (/var/task/dist/server.js:178071:47)
    at n.e.RehydrateStoreService.n.restore (/var/task/dist/server.js:206494:13762)
    at Iksp.e.getInitialState (/var/task/dist/server.js:206494:979474)
    at _callFactory (/var/task/dist/server.js:11245:20)
    at _createProviderInstance$1 (/var/task/dist/server.js:11197:26)
    at initNgModule (/var/task/dist/server.js:11147:28)
    at new NgModuleRef_ (/var/task/dist/server.js:12390:9)
    at Object.createNgModuleRef (/var/task/dist/server.js:12380:12)
```

Document in server side has cookie but in get case throw `Error: NotYetImplemented`
https://github.com/fgnass/domino/blob/master/lib/Document.js#L308
## Specifications

Angular 5

**Comment by CunningFatalist** [comment]
Hey!

Yes, it does not. [There's already an issue for that](https://github.com/7leads/ngx-cookie-service/issues/1). If you happen to  know some things about SSR, feel free to create a PR! 

Cheers
